Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"
  config.vm.box_version = "4.3.12"
  
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provider "vmware_desktop" do |vm|
    vm.memory = "1024"
    vm.cpus = "2"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get upgrade -y

    # Docker
    sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    sudo apt-get update -y
    sudo apt-get install -y docker-ce

    # add user 'vagrant' 
    sudo usermod -aG docker vagrant

    # Node.js (20.x)
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
    sudo apt-get install -y nodejs

    # check and run docker
    sudo systemctl start docker
    sudo systemctl enable docker

    # Nginx
    sudo apt-get install -y nginx

    # check and run nginx
    sudo systemctl start nginx
    sudo systemctl enable nginx
  SHELL

  config.vm.provision "shell", inline: <<-'SHELL'
    cat <<EOL > /etc/nginx/sites-available/default
    server {
      listen 80;
      location / {
          proxy_pass http://localhost:3000;
          proxy_http_version 1.1;
          proxy_set_header Upgrade \$http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host \$host;
          proxy_cache_bypass \$http_upgrade;
      }
    }
EOL
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
    sudo systemctl restart nginx

    # # Pull Docker image
    # docker pull nqthang255/nqthang-express:latest

    # # Run Docker container
    # docker run -d --name nqthang-express -p 3000:3000 --restart unless-stopped nqthang255/nqthang-express:latest
  SHELL
end